owner_name: "tedlasai"
wandb_entity: "coryfan"
patchdir: "/home/featurize/data/patches_48_uint16/"
fulldir: "/home/tedlasai/demosaic/Scenes_npy_removed_bad_uint16/"
odir: "/home/tedlasai/demosaic_network_outputs"
name: "isotropic-64-15-ablation"
model: "isotropic"
num_gpus: 1
backbone: "isotropic"
pattern: "single_quad_nona"
support_width: 2
epochs: 150
split: 4
batchsize: 16
lr: 0.001
load: false
val: 10.0
val_frq: 5
fold: 1
patchnum: 1
patchsz: 48
trimages: 0
chkpointperiod: 1
lrdf: 1.0
lrdp: 25
workers: 14
head: "quad_head_1"
alpha: 0.001
single_head: "single_head_1"
nona_head: "nona_head_1"
normalize_filter: true
remosaic: false
test: false
hard_patches: true
backbone_iso: 100
job_id: null
iso: 3200
width: 48
depth: 64
down: 1
weight_decay: 0
plot_images: false
pass_pattern: false
noisy_viz: false
dropout: 0.05
gauss_sigma: 0.4
range_sigma: 0.0
weight_scale: 0.1
mask_interpolation: false
denoise: false