owner_name: "tedlasai"
wandb_entity: "coryfan"
patchdir: "/home/featurize/data/patches_48_uint16/"
# fulldir: "/home/tedlasai/demosaic/Scenes_npy_removed_bad_uint16/"
odir: "/home/featurize/work/ovt/unidem/demosaic_network_outputs"
load: "models/isotropic_single_quad_nona_isotropic_rm-False_iso3200_bi_100_d0.05_9-13-14-11-43/net.pth"
test: true
model: "isotropic"
name: "isotropictest"
num_gpus: 1
backbone: "convnet"
pattern: "single_quad_nona"
support_width: 2
epochs: 1
batchsize: 16
lr: 0.0001
val: 10.0
val_frq: 1
fold: 1
patchnum: 1
patchsz: 48
trimages: 0
chkpointperiod: 1
lrdf: 1.0
lrdp: 25
workers: 16
head: "quad_head_1"
alpha: 0.001
single_head: "single_head_1"
nona_head: "nona_head_1"
normalize_filter: true
remosaic: false
hard_patches: true
backbone_iso: 100
job_id: null
iso: 3200
width: 64
depth: 64
down: 3
plot_images: false
pass_pattern: false
noisy_viz: false
dropout: 0.0
gauss_sigma: 0.4
range_sigma: 0.0
weight_scale: 0.1
mask_interpolation: false
denoise: false